"""Order Block detection (concept 05).

An OB is the last contiguous run of opposing-direction bars immediately
preceding a displacement leg that ratifies a BoS. Validation requires an FVG
generated by the same leg. HTF anchor enforcement is performed by the PD
Array selector — here we only tag `htf_anchored=False` and let the selector
prune if `require_htf_anchor=True`.
"""

from __future__ import annotations

from dataclasses import dataclass

from ict_bot.data.models import Bars
from ict_bot.signals.base import FVG, Direction, Interval, Leg, OrderBlock


@dataclass(frozen=True, slots=True)
class OrderBlockConfig:
    max_run_bars: int = 4
    extremum_fallback_lookback: int = 5
    require_fvg_on_following_leg: bool = True


def _bar_dir(opens: list[float], closes: list[float], t: int) -> Direction | None:
    if closes[t] > opens[t]:
        return Direction.BULL
    if closes[t] < opens[t]:
        return Direction.BEAR
    return None


def detect_order_blocks(
    bars: Bars,
    legs: list[Leg],
    fvgs: list[FVG],
    *,
    config: OrderBlockConfig | None = None,
) -> list[OrderBlock]:
    """Return all OBs produced by displacement legs that left an FVG."""
    cfg = config or OrderBlockConfig()
    if bars.empty or not legs:
        return []
    opens = bars.df.get_column("open").to_list()
    highs = bars.df.get_column("high").to_list()
    lows = bars.df.get_column("low").to_list()
    closes = bars.df.get_column("close").to_list()

    out: list[OrderBlock] = []
    for leg in legs:
        leg_fvgs = [
            g for g in fvgs
            if g.direction == leg.direction
            and leg.start_index <= g.anchor_index <= leg.end_index
        ]
        if cfg.require_fvg_on_following_leg and not leg_fvgs:
            continue
        fvg_ref = leg_fvgs[0] if leg_fvgs else None

        opp = Direction.BEAR if leg.direction == Direction.BULL else Direction.BULL
        # Walk back from leg.start - 1
        run: list[int] = []
        i = leg.start_index - 1
        while i >= 0 and _bar_dir(opens, closes, i) == opp and len(run) < cfg.max_run_bars:
            run.append(i)
            i -= 1
        if not run:
            # Fallback: extremum bar in lookback window
            lookback_start = max(0, leg.start_index - cfg.extremum_fallback_lookback)
            window = list(range(lookback_start, leg.start_index))
            if not window:
                continue
            if leg.direction == Direction.BULL:
                pick = min(window, key=lambda k: lows[k])
            else:
                pick = max(window, key=lambda k: highs[k])
            run = [pick]

        ob_low = min(lows[k] for k in run)
        ob_high = max(highs[k] for k in run)
        out.append(
            OrderBlock(
                direction=leg.direction,
                anchor_index=min(run),
                range=Interval(low=ob_low, high=ob_high),
                leg_ref=leg,
                fvg_ref=fvg_ref,
                htf_anchored=False,  # selector decides
            ),
        )
    return out


def invalidate_order_blocks(bars: Bars, obs: list[OrderBlock]) -> list[OrderBlock]:
    """Mark `invalidated_at` on each OB once a body close beyond MT in the
    opposing direction occurs."""
    if not obs or bars.empty:
        return obs
    opens = bars.df.get_column("open").to_list()
    closes = bars.df.get_column("close").to_list()
    m = len(opens)
    out: list[OrderBlock] = []
    for ob in obs:
        inv = ob.invalidated_at
        if inv is None:
            start = ob.anchor_index + 1
            for s in range(start, m):
                body_top = max(opens[s], closes[s])
                body_bot = min(opens[s], closes[s])
                if ob.direction == Direction.BULL and body_bot < ob.mt:
                    inv = s
                    break
                if ob.direction == Direction.BEAR and body_top > ob.mt:
                    inv = s
                    break
        out.append(
            OrderBlock(
                direction=ob.direction,
                anchor_index=ob.anchor_index,
                range=ob.range,
                leg_ref=ob.leg_ref,
                fvg_ref=ob.fvg_ref,
                htf_anchored=ob.htf_anchored,
                touch_count=ob.touch_count,
                invalidated_at=inv,
            ),
        )
    return out
